#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

display_info() {
    sub_domain=$1
    domain=$2
    record_type=$(dig $sub_domain.$domain | awk '/ANSWER SECTION:/{getline; print $4}')
    destination=$(dig $sub_domain.$domain | awk '/ANSWER SECTION:/{getline; print $5}')
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

main() {
    domain=$1
    sub_domain=$2

    if [ -z "$sub_domain" ]; then
        sub_domain_list=("www" "lb-01" "web-01" "web-02")
    else
        sub_domain_list=("$sub_domain")
    fi

    for sub in "${sub_domain_list[@]}"; do
        display_info $sub $domain
    done
}

main "$@"
