#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Install Certbot
sudo apt-get install -y certbot

# Obtain SSL certificate using Certbot
sudo certbot certonly --standalone -d www.holberton.online

# Create HAProxy config file
sudo tee /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL).
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.holberton.online/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    acl is_holberton hdr_end(host) -i www.holberton.online
    use_backend holberton_backend if is_holberton

backend holberton_backend
    mode http
    server web-server-1 <web-01-IP>:80 check
EOF

# Restart HAProxy to apply changes
sudo service haproxy restart
