#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y nginx

# Create a new Nginx configuration file for redirection
echo "server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional server configurations can be added here if needed
}" | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the new site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default Nginx default server block
sudo rm -f /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
