#!/usr/bin/env bash
# This script configures Apache to return a page containing Hello Holberton

# Update package information
apt-get update

# Install Apache
apt-get install -y apache2

# Create the Hello Holberton page
echo "Hello Holberton" > /var/www/html/index.html

# Start Apache
service apache2 start

# Ensure Apache starts on system boot
update-rc.d apache2 defaults
